import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {OBJLoader} from 'three/addons/loaders/OBJLoader.js';
import {STLLoader} from 'three/addons/loaders/STLLoader.js';
import {GLTFExporter} from 'three/addons/exporters/GLTFExporter.js';

const $=s=>document.querySelector(s), canvas=$('#canvas'), viewport=$('#viewport');
const renderer=new THREE.WebGLRenderer({canvas,antialias:true}); renderer.setPixelRatio(Math.min(devicePixelRatio,2)); renderer.shadowMap.enabled=true;
const scene=new THREE.Scene(); scene.background=new THREE.Color(0x101010);
const camera=new THREE.PerspectiveCamera(45,1,.01,2000); camera.position.set(8,6,10);
const controls=new OrbitControls(camera,canvas); controls.enableDamping=true;
scene.add(new THREE.HemisphereLight(0xffffff,0x333333,2)); const dl=new THREE.DirectionalLight(0xffffff,3);dl.position.set(6,10,8);scene.add(dl);
const grid=new THREE.GridHelper(30,30,0x555555,0x292929);scene.add(grid);
let modelRoot=null, voxelMesh=null, meshes=[], sourceName='model';
const raycaster=new THREE.Raycaster(); const dir=new THREE.Vector3(1,.000371,.000733).normalize();
function resize(){const w=viewport.clientWidth,h=viewport.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()} addEventListener('resize',resize);resize();
(function loop(){controls.update();renderer.render(scene,camera);requestAnimationFrame(loop)})();
function disposeObj(o){if(!o)return;o.traverse?.(x=>{x.geometry?.dispose?.();if(Array.isArray(x.material))x.material.forEach(m=>m.dispose());else x.material?.dispose?.()});scene.remove(o)}
function fit(){if(!modelRoot)return;const b=new THREE.Box3().setFromObject(modelRoot),s=b.getSize(new THREE.Vector3()),c=b.getCenter(new THREE.Vector3());const d=Math.max(s.x,s.y,s.z);controls.target.copy(c);camera.position.copy(c).add(new THREE.Vector3(1,0.75,1).normalize().multiplyScalar(d*2.2));camera.near=Math.max(d/1000,.001);camera.far=d*100;camera.updateProjectionMatrix();controls.update()}
async function loadFile(file){sourceName=file.name.replace(/\.[^.]+$/,''); $('#status').textContent='Loading…';disposeObj(modelRoot);disposeObj(voxelMesh);voxelMesh=null;meshes=[];const ext=file.name.split('.').pop().toLowerCase(),url=URL.createObjectURL(file);try{if(ext==='glb'||ext==='gltf'){const g=await new GLTFLoader().loadAsync(url);modelRoot=g.scene}else if(ext==='obj'){modelRoot=await new OBJLoader().loadAsync(url)}else if(ext==='stl'){const geo=await new STLLoader().loadAsync(url);modelRoot=new THREE.Group();modelRoot.add(new THREE.Mesh(geo,new THREE.MeshStandardMaterial({color:0x999999,side:THREE.DoubleSide})))}else throw Error('Unsupported format');
modelRoot.traverse(o=>{if(o.isMesh){o.material=o.material?.clone?.()||new THREE.MeshStandardMaterial();o.material.side=THREE.DoubleSide;meshes.push(o)}});modelRoot.updateMatrixWorld(true);scene.add(modelRoot);fit();$('#voxelize').disabled=false;$('#export').disabled=true;$('#stats').textContent=`${file.name} · ${meshes.length} mesh(es)`;$('#status').textContent='Ready.';applyOriginal()}catch(e){console.error(e);$('#status').textContent='Could not load this model.'}finally{URL.revokeObjectURL(url)}}
function applyOriginal(){if(!modelRoot)return;modelRoot.visible=$('#original').checked;meshes.forEach(m=>m.material.wireframe=$('#wire').checked)}
function pointInside(p){let hits=[];for(const m of meshes){raycaster.set(p,dir);hits.push(...raycaster.intersectObject(m,false))}hits.sort((a,b)=>a.distance-b.distance);let unique=0,last=-Infinity;for(const h of hits){if(h.distance-last>1e-5){unique++;last=h.distance}}return unique%2===1}
function nearSurface(p,half){const dirs=[new THREE.Vector3(1,0,0),new THREE.Vector3(-1,0,0),new THREE.Vector3(0,1,0),new THREE.Vector3(0,-1,0),new THREE.Vector3(0,0,1),new THREE.Vector3(0,0,-1)];for(const d of dirs){raycaster.set(p,d);raycaster.far=half*1.05;for(const m of meshes)if(raycaster.intersectObject(m,false).length)return true}return false}
async function voxelize(){if(!modelRoot)return;$('#voxelize').disabled=true;$('#export').disabled=true;$('#status').textContent='Calculating voxels…';await new Promise(r=>setTimeout(r,30));modelRoot.updateMatrixWorld(true);const box=new THREE.Box3().setFromObject(modelRoot),step=+$('#voxel').value,scale=+$('#cubeScale').value,mode=$('#mode').value;const size=box.getSize(new THREE.Vector3()), nx=Math.ceil(size.x/step),ny=Math.ceil(size.y/step),nz=Math.ceil(size.z/step),total=nx*ny*nz;if(total>1200000){$('#status').textContent=`Grid too dense (${total.toLocaleString()} cells). Increase voxel size.`;$('#voxelize').disabled=false;return}const positions=[];let n=0;for(let ix=0;ix<nx;ix++){const x=box.min.x+(ix+.5)*step;for(let iy=0;iy<ny;iy++){const y=box.min.y+(iy+.5)*step;for(let iz=0;iz<nz;iz++){const z=box.min.z+(iz+.5)*step,p=new THREE.Vector3(x,y,z);if(mode==='solid'?pointInside(p):nearSurface(p,step*.7))positions.push(p);n++}if(iy%5===0){$('#status').textContent=`Calculating… ${Math.round(n/total*100)}%`;await new Promise(r=>setTimeout(r,0))}}}
disposeObj(voxelMesh);const geo=new THREE.BoxGeometry(step*scale,step*scale,step*scale),mat=new THREE.MeshStandardMaterial({color:0xffc83d,roughness:.75});voxelMesh=new THREE.InstancedMesh(geo,mat,positions.length);const dummy=new THREE.Object3D();positions.forEach((p,i)=>{dummy.position.copy(p);dummy.updateMatrix();voxelMesh.setMatrixAt(i,dummy.matrix)});voxelMesh.instanceMatrix.needsUpdate=true;scene.add(voxelMesh);$('#stats').textContent=`${sourceName} · ${positions.length.toLocaleString()} voxels · grid ${nx}×${ny}×${nz}`;$('#status').textContent='Done.';$('#voxelize').disabled=false;$('#export').disabled=positions.length===0}
async function exportGLB(){if(!voxelMesh)return;$('#status').textContent='Exporting GLB…';const group=new THREE.Group();group.add(voxelMesh.clone());new GLTFExporter().parse(group,res=>{const blob=new Blob([res],{type:'model/gltf-binary'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${sourceName}_voxels.glb`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);$('#status').textContent='Exported.'},e=>{$('#status').textContent='Export failed.';console.error(e)},{binary:true,onlyVisible:true})}
$('#file').onchange=e=>e.target.files[0]&&loadFile(e.target.files[0]);const drop=$('#drop');['dragenter','dragover'].forEach(x=>drop.addEventListener(x,e=>{e.preventDefault();drop.classList.add('drag')}));['dragleave','drop'].forEach(x=>drop.addEventListener(x,e=>{e.preventDefault();drop.classList.remove('drag')}));drop.addEventListener('drop',e=>e.dataTransfer.files[0]&&loadFile(e.dataTransfer.files[0]));
$('#voxel').oninput=e=>$('#voxelOut').value=e.target.value;$('#cubeScale').oninput=e=>$('#scaleOut').value=e.target.value;$('#original').onchange=applyOriginal;$('#wire').onchange=applyOriginal;$('#voxelize').onclick=voxelize;$('#export').onclick=exportGLB;$('#reset').onclick=fit;