import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {OBJLoader} from 'three/addons/loaders/OBJLoader.js';
import {STLLoader} from 'three/addons/loaders/STLLoader.js';
import {FBXLoader} from 'three/addons/loaders/FBXLoader.js';
import {OBJExporter} from 'three/addons/exporters/OBJExporter.js';
import {GLTFExporter} from 'three/addons/exporters/GLTFExporter.js';

const $=s=>document.querySelector(s), canvas=$('#canvas'), viewport=$('#viewport');
const renderer=new THREE.WebGLRenderer({canvas,antialias:true}); renderer.setPixelRatio(Math.min(devicePixelRatio,2)); renderer.shadowMap.enabled=true;
const scene=new THREE.Scene(); scene.background=new THREE.Color(0x101010);
const camera=new THREE.PerspectiveCamera(45,1,.01,2000); camera.position.set(8,6,10);
const controls=new OrbitControls(camera,canvas); controls.enableDamping=true;
// Maya-style navigation: Alt+LMB rotate, Alt+MMB pan, Alt+RMB dolly.
controls.mouseButtons.LEFT=null; controls.mouseButtons.MIDDLE=THREE.MOUSE.PAN; controls.mouseButtons.RIGHT=THREE.MOUSE.PAN;
scene.add(new THREE.HemisphereLight(0xffffff,0x333333,2)); const dl=new THREE.DirectionalLight(0xffffff,3);dl.position.set(6,10,8);scene.add(dl);
const grid=new THREE.GridHelper(30,30,0x555555,0x292929);scene.add(grid);
let modelRoot=null, voxelMesh=null, meshes=[], sourceName='model', voxelPositions=[], voxelColors=[], sliceEnabled=false, xrayEnabled=false;
const PALETTE={
 Blue:{color:'#45C9FF',shadow:'#2B3E89'}, Brown:{color:'#875530',shadow:'#89542B'},
 Green:{color:'#58D65A',shadow:'#2D4316'}, Orange:{color:'#FF952A',shadow:'#89632B'},
 PowerPink:{color:'#FF6490',shadow:'#892B52'}, Purple:{color:'#C18DFF',shadow:'#632B89'},
 Red:{color:'#FF5940',shadow:'#6C0D08'}, Yellow:{color:'#FFC845',shadow:'#C58400'}
};
let activeMat='Yellow', customColor=PALETTE.Yellow.color, customShadow=PALETTE.Yellow.shadow;
const raycaster=new THREE.Raycaster(); const dir=new THREE.Vector3(1,.000371,.000733).normalize();
function resize(){const w=viewport.clientWidth,h=viewport.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()} addEventListener('resize',resize);resize();
(function loop(){controls.update();renderer.render(scene,camera);requestAnimationFrame(loop)})();
function disposeObj(o){if(!o)return;o.traverse?.(x=>{x.geometry?.dispose?.();if(Array.isArray(x.material))x.material.forEach(m=>m.dispose());else x.material?.dispose?.()});scene.remove(o)}
function fit(){if(!modelRoot)return;const b=new THREE.Box3().setFromObject(modelRoot),s=b.getSize(new THREE.Vector3()),c=b.getCenter(new THREE.Vector3());const d=Math.max(s.x,s.y,s.z);controls.target.copy(c);camera.position.copy(c).add(new THREE.Vector3(1,0.75,1).normalize().multiplyScalar(d*2.2));camera.near=Math.max(d/1000,.001);camera.far=d*100;camera.updateProjectionMatrix();controls.update()}
async function loadFile(file){sourceName=file.name.replace(/\.[^.]+$/,''); $('#status').textContent='Loading…';disposeObj(modelRoot);disposeObj(voxelMesh);voxelMesh=null;meshes=[];const ext=file.name.split('.').pop().toLowerCase(),url=URL.createObjectURL(file);try{if(ext==='glb'||ext==='gltf'){const g=await new GLTFLoader().loadAsync(url);modelRoot=g.scene}else if(ext==='obj'){modelRoot=await new OBJLoader().loadAsync(url)}else if(ext==='fbx'){modelRoot=await new FBXLoader().loadAsync(url)}else if(ext==='stl'){const geo=await new STLLoader().loadAsync(url);modelRoot=new THREE.Group();modelRoot.add(new THREE.Mesh(geo,new THREE.MeshStandardMaterial({color:0x999999,side:THREE.DoubleSide})))}else throw Error('Unsupported format');
modelRoot.traverse(o=>{if(o.isMesh){o.material=o.material?.clone?.()||new THREE.MeshStandardMaterial();o.material.side=THREE.DoubleSide;meshes.push(o)}});modelRoot.updateMatrixWorld(true);scene.add(modelRoot);fit();$('#voxelize').disabled=false;$('#export').disabled=true;$('#stats').textContent=`${file.name} · ${meshes.length} mesh(es)`;$('#status').textContent='Ready.';applyOriginal()}catch(e){console.error(e);$('#status').textContent='Could not load this model.'}finally{URL.revokeObjectURL(url)}}
function applyOriginal(){if(!modelRoot)return;modelRoot.visible=$('#original').checked;meshes.forEach(m=>m.material.wireframe=$('#wire').checked)}
function pointInside(p){let hits=[];for(const m of meshes){raycaster.set(p,dir);hits.push(...raycaster.intersectObject(m,false))}hits.sort((a,b)=>a.distance-b.distance);let unique=0,last=-Infinity;for(const h of hits){if(h.distance-last>1e-5){unique++;last=h.distance}}return unique%2===1}
function nearSurface(p,half){const dirs=[new THREE.Vector3(1,0,0),new THREE.Vector3(-1,0,0),new THREE.Vector3(0,1,0),new THREE.Vector3(0,-1,0),new THREE.Vector3(0,0,1),new THREE.Vector3(0,0,-1)];for(const d of dirs){raycaster.set(p,d);raycaster.far=half*1.05;for(const m of meshes)if(raycaster.intersectObject(m,false).length)return true}return false}
async function voxelize(){if(!modelRoot)return;$('#voxelize').disabled=true;$('#export').disabled=true;$('#status').textContent='Calculating voxels…';await new Promise(r=>setTimeout(r,30));modelRoot.updateMatrixWorld(true);const box=new THREE.Box3().setFromObject(modelRoot),step=+$('#voxel').value,scale=+$('#cubeScale').value,mode=$('#mode').value;const size=box.getSize(new THREE.Vector3()), nx=Math.ceil(size.x/step),ny=Math.ceil(size.y/step),nz=Math.ceil(size.z/step),total=nx*ny*nz;if(total>1200000){$('#status').textContent=`Grid too dense (${total.toLocaleString()} cells). Increase voxel size.`;$('#voxelize').disabled=false;return}const positions=[];let n=0;for(let ix=0;ix<nx;ix++){const x=box.min.x+(ix+.5)*step;for(let iy=0;iy<ny;iy++){const y=box.min.y+(iy+.5)*step;for(let iz=0;iz<nz;iz++){const z=box.min.z+(iz+.5)*step,p=new THREE.Vector3(x,y,z);if(mode==='solid'?pointInside(p):nearSurface(p,step*.7))positions.push(p);n++}if(iy%5===0){$('#status').textContent=`Calculating… ${Math.round(n/total*100)}%`;await new Promise(r=>setTimeout(r,0))}}}
disposeObj(voxelMesh);const geo=new THREE.BoxGeometry(step*scale,step*scale,step*scale),mat=new THREE.MeshStandardMaterial({color:customColor,emissive:customShadow,emissiveIntensity:.16,roughness:.75});voxelMesh=new THREE.InstancedMesh(geo,mat,positions.length);voxelPositions=positions.map(p=>p.clone());voxelColors=positions.map(()=>customColor);const dummy=new THREE.Object3D(),baseCol=new THREE.Color(customColor);positions.forEach((p,i)=>{dummy.position.copy(p);dummy.updateMatrix();voxelMesh.setMatrixAt(i,dummy.matrix);voxelMesh.setColorAt(i,baseCol)});voxelMesh.instanceMatrix.needsUpdate=true;if(voxelMesh.instanceColor)voxelMesh.instanceColor.needsUpdate=true;scene.add(voxelMesh);if(sliceEnabled)updateSlice();$('#stats').textContent=`${sourceName} · ${positions.length.toLocaleString()} voxels · grid ${nx}×${ny}×${nz}`;$('#status').textContent='Done.';$('#voxelize').disabled=false;$('#export').disabled=positions.length===0}
function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function exportGLB(){if(!voxelMesh)return;$('#status').textContent='Exporting GLB…';const group=new THREE.Group();group.add(voxelMesh.clone());new GLTFExporter().parse(group,res=>{const blob=new Blob([res],{type:'model/gltf-binary'});downloadBlob(blob,`${sourceName}_voxels.glb`);$('#status').textContent='Exported GLB.'},e=>{$('#status').textContent='Export failed.';console.error(e)},{binary:true,onlyVisible:true})}
function applyVoxelMaterial(){if(!voxelMesh)return;voxelMesh.material.color.set(0xffffff);voxelMesh.material.emissive.set(customShadow);voxelMesh.material.transparent=xrayEnabled;voxelMesh.material.opacity=xrayEnabled?(+$('#xrayOpacity').value/100):1;voxelMesh.material.depthWrite=!xrayEnabled;voxelMesh.material.needsUpdate=true}
function syncMatEditor(){const c=$('#colorPicker'),s=$('#shadowPicker'),ct=$('#colorHex'),st=$('#shadowHex');if(!c)return;c.value=customColor;s.value=customShadow;ct.value=customColor.toUpperCase();st.value=customShadow.toUpperCase()}
function validHex(v){v=v.trim();if(!v.startsWith('#'))v='#'+v;return /^#[0-9a-f]{6}$/i.test(v)?v.toUpperCase():null}
function setCustom(which,value){const v=validHex(value);if(!v)return;if(which==='color')customColor=v;else customShadow=v;syncMatEditor();applyVoxelMaterial()}
function buildPalette(){const el=$('#palette');for(const [name,p] of Object.entries(PALETTE)){const b=document.createElement('button');b.type='button';b.className='mat-swatch'+(name===activeMat?' active':'');b.title=`${name} · ${p.color} / ${p.shadow}`;b.innerHTML=`<span class="mat-ball" style="--c:${p.color};--s:${p.shadow}"></span><small>${name}</small>`;b.onclick=()=>{activeMat=name;customColor=p.color;customShadow=p.shadow;document.querySelectorAll('.mat-swatch').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#matInfo').innerHTML=`Preset: <b>${name}</b>`;syncMatEditor();applyVoxelMaterial()};el.appendChild(b)}const p=PALETTE[activeMat];$('#matInfo').innerHTML=`Preset: <b>${activeMat}</b>`;syncMatEditor()}
buildPalette();
$('#colorPicker').oninput=e=>setCustom('color',e.target.value);$('#shadowPicker').oninput=e=>setCustom('shadow',e.target.value);$('#colorHex').onchange=e=>setCustom('color',e.target.value);$('#shadowHex').onchange=e=>setCustom('shadow',e.target.value);
let paintEnabled=false,painting=false,paintThrough=false;
const paintRay=new THREE.Raycaster(),mouse=new THREE.Vector2();
function updateSlice(){if(!voxelMesh)return;const axis=$('#sliceAxis').value,dirn=+$('#sliceDir').value,percent=+$('#sliceDepth').value/100;const box=new THREE.Box3();voxelPositions.forEach(p=>box.expandByPoint(p));const min=box.min[axis],max=box.max[axis],cut=min+(max-min)*percent;const dummy=new THREE.Object3D();for(let i=0;i<voxelPositions.length;i++){const p=voxelPositions[i],show=!sliceEnabled||(dirn>0?p[axis]<=cut:p[axis]>=cut);dummy.position.copy(p);dummy.quaternion.identity();dummy.scale.setScalar(show?1:0);dummy.updateMatrix();voxelMesh.setMatrixAt(i,dummy.matrix)}voxelMesh.instanceMatrix.needsUpdate=true;voxelMesh.computeBoundingSphere();$('#sliceOut').value=Math.round(percent*100)+'%'}
function resetSliceMatrices(){if(!voxelMesh)return;const dummy=new THREE.Object3D();for(let i=0;i<voxelPositions.length;i++){dummy.position.copy(voxelPositions[i]);dummy.quaternion.identity();dummy.scale.set(1,1,1);dummy.updateMatrix();voxelMesh.setMatrixAt(i,dummy.matrix)}voxelMesh.instanceMatrix.needsUpdate=true}
function paintAt(ev){if(!paintEnabled||!voxelMesh)return;const rect=canvas.getBoundingClientRect();mouse.x=((ev.clientX-rect.left)/rect.width)*2-1;mouse.y=-((ev.clientY-rect.top)/rect.height)*2+1;paintRay.setFromCamera(mouse,camera);const hits=paintRay.intersectObject(voxelMesh,false);if(!hits.length)return;const first=hits.find(h=>h.instanceId!=null);if(!first)return;const radius=Math.max(0,+$('#brushSize').value|0),step=+$('#voxel').value,col=new THREE.Color(customColor),ids=new Set();if(paintThrough){const ray=paintRay.ray,brushWorld=Math.max(step*.55,radius*step+step*.55),maxDepth=Math.max(0,+$('#paintDepth').value|0)*step;const originT=ray.direction.dot(voxelPositions[first.instanceId].clone().sub(ray.origin));for(let i=0;i<voxelPositions.length;i++){const p=voxelPositions[i],v=p.clone().sub(ray.origin),t=v.dot(ray.direction);if(t<originT-step*.6)continue;if(maxDepth>0&&t>originT+maxDepth+step*.6)continue;const closest=ray.origin.clone().addScaledVector(ray.direction,t);if(p.distanceTo(closest)<=brushWorld)ids.add(i)}}else{const center=voxelPositions[first.instanceId];for(let i=0;i<voxelPositions.length;i++){const p=voxelPositions[i];if(Math.abs(p.x-center.x)<=radius*step+.001&&Math.abs(p.y-center.y)<=radius*step+.001&&Math.abs(p.z-center.z)<=radius*step+.001)ids.add(i)}}for(const i of ids){voxelMesh.setColorAt(i,col);voxelColors[i]=customColor}if(voxelMesh.instanceColor)voxelMesh.instanceColor.needsUpdate=true}
let mayaNav=false,navLastX=0,navLastY=0;
canvas.addEventListener('pointerdown',e=>{if(!paintEnabled)return;if(e.altKey&&e.button===0){e.preventDefault();painting=false;mayaNav=true;navLastX=e.clientX;navLastY=e.clientY;controls.enabled=false;canvas.setPointerCapture?.(e.pointerId);return}if(e.button===0){painting=true;controls.enabled=false;paintAt(e)}else{painting=false;controls.enabled=true}});
canvas.addEventListener('pointermove',e=>{if(mayaNav){e.preventDefault();const dx=e.clientX-navLastX,dy=e.clientY-navLastY;navLastX=e.clientX;navLastY=e.clientY;const off=camera.position.clone().sub(controls.target),sph=new THREE.Spherical().setFromVector3(off);sph.theta-=dx*0.008;sph.phi-=dy*0.008;sph.phi=Math.max(0.01,Math.min(Math.PI-0.01,sph.phi));off.setFromSpherical(sph);camera.position.copy(controls.target).add(off);camera.lookAt(controls.target);return}if(painting&&(e.buttons&1))paintAt(e)});
addEventListener('pointerup',()=>{painting=false;mayaNav=false;controls.enabled=true});
$('#paintMode').onchange=e=>{paintEnabled=e.target.checked;canvas.style.cursor=paintEnabled?'crosshair':'grab';$('#status').textContent=paintEnabled?'Paint: Left drag. Rotate: Middle drag or Alt+Left. Pan: Right drag. Wheel: Zoom.':'Paint mode off.'};
$('#brushSize').oninput=e=>$('#brushOut').value=e.target.value;
$('#paintThrough').onchange=e=>{paintThrough=e.target.checked;$('#paintThroughControls').classList.toggle('disabled',!paintThrough);$('#status').textContent=paintThrough?'Paint Through: brush paints from the visible hit into interior voxels along the camera ray.':'Paint Through off.'};
$('#paintDepth').oninput=e=>$('#paintDepthOut').value=e.target.value==='0'?'ALL':e.target.value+' layers';
$('#sliceMode').onchange=e=>{sliceEnabled=e.target.checked;updateSlice();$('#status').textContent=sliceEnabled?'Slice mode: hidden voxels are not deleted. Paint the exposed inside.':'Slice mode off.'};
$('#sliceDepth').oninput=updateSlice;$('#sliceAxis').onchange=updateSlice;$('#sliceDir').onchange=updateSlice;
$('#xrayMode').onchange=e=>{xrayEnabled=e.target.checked;applyVoxelMaterial();$('#xrayControls').classList.toggle('disabled',!xrayEnabled);$('#status').textContent=xrayEnabled?'X-Ray: see interior colors while painting. Use Slice when you need to select a buried voxel.':'X-Ray off.'};
$('#xrayOpacity').oninput=e=>{$('#xrayOut').value=e.target.value+'%';applyVoxelMaterial()};
function exportOBJ(){if(!voxelMesh)return;$('#status').textContent='Preparing geometry export…';const group=new THREE.Group(),geo=voxelMesh.geometry,mat=new THREE.Matrix4();for(let i=0;i<voxelMesh.count;i++){voxelMesh.getMatrixAt(i,mat);const g=geo.clone();g.applyMatrix4(mat);group.add(new THREE.Mesh(g))}const data=new OBJExporter().parse(group);downloadBlob(new Blob([data],{type:'text/plain'}),`${sourceName}_voxels.obj`);group.traverse(o=>o.geometry?.dispose?.());$('#status').textContent='Exported OBJ. Import this OBJ into Maya, then Export Selection as FBX.'}
function exportSelected(){const fmt=$('#exportFormat').value;if(fmt==='glb')exportGLB();else exportOBJ()}
$('#file').onchange=e=>e.target.files[0]&&loadFile(e.target.files[0]);const drop=$('#drop');['dragenter','dragover'].forEach(x=>drop.addEventListener(x,e=>{e.preventDefault();drop.classList.add('drag')}));['dragleave','drop'].forEach(x=>drop.addEventListener(x,e=>{e.preventDefault();drop.classList.remove('drag')}));drop.addEventListener('drop',e=>e.dataTransfer.files[0]&&loadFile(e.dataTransfer.files[0]));
$('#voxel').oninput=e=>$('#voxelOut').value=e.target.value;$('#cubeScale').oninput=e=>$('#scaleOut').value=e.target.value;$('#original').onchange=applyOriginal;$('#wire').onchange=applyOriginal;$('#voxelize').onclick=voxelize;$('#export').onclick=exportSelected;$('#reset').onclick=fit;